### PR TITLE
Converts the project into a composer based autoloading project.

### PR DESCRIPTION
**Pull request by ghost**
Let me know if this is approach is something that you all would be interested in implementing, I can continue the refactoring is this seems worth it.

### CODE REVIEW

**Comment by justinvforvendetta** [comment]
@miguelsolano absolutely, i like where it's going. i cant merge this though, as its incomplete, but i get what you're doing and i dig it.

**Comment by ghost** [comment]
@justinvforvendetta Awesome, i'll keep working on it then 👍

**Comment by justinvforvendetta** [comment]
@miguelsolano made a few changes an hour or two ago, so make sure you pull them before pushing =]

**Comment by Positivism** [comment]
Unsure if you still plan on doing this but if you do `class JSONRPCClient { ` should be `class JsonRpcClient` to abide by PSR 1 #3 "all class names must be declared in StudlyCaps".

**Pull request closed without merging**
